#!/bin/bash

# https://exain.wordpress.com/2011/03/31/making-a-wifi-hotspot-access-point-using-linux-wifi-lan-cardusb-adapter/

conf=ap.conf.$$
hostapd=$HOME/bin/hostapd

function ap/exit() {
  if test -r "${conf}" ; then
    rm ${conf}
  fi
  exit 1
}
trap ap/exit EXIT

function ap/genpw() {
  local l=${1:-21}
  [ "$l" == "" ] && l=16
  tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${l} | xargs
}

function ap/config() {
  cat > ${conf} <<EOF
interface=${1:-${inb}}
driver=nl80211
ssid=${essid}
hw_mode=g
channel=6
macaddr_acl=0
ignore_broadcast_ssid=0
auth_algs=1
wpa=1
wpa_passphrase=${passw}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
wpa_ptk_rekey=600
EOF
}



function ap/ipmasq() {
  # ! interface
  echo "1" | sudo tee /proc/sys/net/ipv4/ip_forward
  sudo iptables -t nat -A POSTROUTING -o ${outb} -j MASQUERADE
}


### args
# _cmd=${1:-start}
_wif=${1:-wlan1}
passw=${2:-$(ap/genpw)}

### main
if test -z "${essid}" ; then
  read    -p "ESSID: " essid
else
  echo "ESSID: ${essid}"
fi
echo "     > $passw"
read

v/wifup ${_wif}
sleep 1

# sudo iwconfig ${_wif} mode master
sudo ifconfig ${_wif} 10.1.1.1 netmask 255.255.255.0 

ap/config ${_wif}
echo ""
echo ""
sudo ${hostapd} -t -dd ${conf}
