#!/bin/bash
source config

# sshd_config
# ListenAddress 10.0.2.15
# ListenAddress 192.168.33.33

if test -r ${identity} ; then
  opt="-i ${identity}"
fi

scp ${opt} $* ${user}@${host_only}:/home/${user}

