#!/bin/bash
# will disable vagrant's eth0
# /vagrant and VB sharing seems to work

pid=/var/run/wicd/wicd.pid
if test -r "${pid}" ; then
  echo "wcid is running"
else
  sudo wicd
fi
sudo wicd-client -n
