#!/bin/bash
wif=${*:-wlan0}

for if in ${wif} ; do
  echo ""
  echo "Configuring: $if"
  ifconfig $if &>/dev/null
  if test $? -eq 0 ; then
    sudo ifconfig $if down
  fi
  sudo macchanger -r $if
  sudo ifconfig $if up
done

