#!/bin/bash
wif=${*:-wlan0}

function wifup/genpw() {
  local l=${1:-8}
  [ "$l" == "" ] && l=16
  tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${l} | xargs
}


function wifup/wait() {
  local _if=${1}
  while true; do
    iwconfig ${_if} &>/dev/null
    if test $? -eq 0 ; then
      return
    fi
    local _d=$(date +"%Y-%m-%d %H:%M:%S")
    echo "${_d} Connect device: ${_if} !"
    sleep 3
  done
}

for if in ${wif} ; do
  wifup/wait ${if}
  echo ""
  echo "Configuring: $if..."
  ifconfig $if &>/dev/null
  if test $? -eq 0 ; then
    sudo ifconfig $if down
  fi
  sudo macchanger -r $if
  sudo ifconfig $if up
  # sudo iwconfig $if nickname "$(wifup/genpw)"
done
