#!/bin/bash

# http://linux.icydog.net/wpa.php

_conf=wpa.conf.$$
_wdrv=wext
# green line
_wif=wlan0

function wpa/connect() {
  v/wifup
  sleep 1
  bssid=""

  while test "${bssid}" = "" ; do
    echo ""
    echo "Scanning..."
    # v/scan
    v/cells
    echo ""
    read    -p "ESSID: " bssid
    if test "${bssid}" = "" ; then
      continue
    fi
    read -s -p "     > " passw
    break
  done

  echo ""
  echo "Connecting..."
  wpa_passphrase "${bssid}" "${passw}" > "${_conf}"
  sudo wpa_supplicant -D${_wdrv} -i${_wif} -c${_conf}

  sudo rm ${_conf}
}

function wpa/dhcp() {
  sudo dhclient ${_wif}
  ifconfig ${_wif}
  route -n
}

_cmd=$1
shift

case ${_cmd} in
  dhcp)
    wpa/dhcp
  ;;
  me)
    curl -s ifconfig.me/all.json | \
    v/prettify_json.rb
  ;;
  ip)
    ip -o -4 addr show ${_wif}
  ;;
  *)
    wpa/connect $*
  ;;
esac
