#!/bin/bash

# http://linux.icydog.net/wpa.php

_conf=wpa.conf.$$
_wdrv=wext
# green line
_wif=wlan0

function wpa/connect() {
  _wif=$1
  v/wifup ${_wif}
  sleep 1
  bssid=""

  while test "${bssid}" = "" ; do
    echo ""
    echo "Scanning..."
    # v/scan
    v/cells ${_wif}
    echo ""
    read    -p "ESSID: " bssid
    if test "${bssid}" = "" ; then
      continue
    fi
    read -s -p "     > " passw
    break
  done

  echo ""
  echo "Connecting..."
  wpa_passphrase "${bssid}" "${passw}" > "${_conf}"
  sudo wpa_supplicant -D${_wdrv} -i${_wif} -c${_conf}

  sudo rm ${_conf}
}

function wpa/dhcp() {
  local _if=${1:-${_wif}}
  sudo dhclient ${_if}
  ifconfig ${_if}
  route -n
}

_cmd=$1

case ${_cmd} in
  dhcp)
    shift
    wpa/dhcp $*
  ;;
  me)
    curl -s ifconfig.me/all.json | \
    v/prettify_json.rb
  ;;
  ip)
    ip -o -4 addr show ${_wif}
  ;;
  *)
    wpa/connect $*
  ;;
esac
