#!/bin/bash

cd ${1}

torgate_pid="torgate.pid"
privoxy_pid="privoxy.pid"

echo $$ > ${torgate_pid}

function torgate/exit() {
  source config
  echo "Stopping privoxy..."

  if test -r ${privoxy_pid} ; then
    local _pid=$(cat ${privoxy_pid})
    if ! test -z "${_pid}" ; then kill ${_pid}; fi
  fi
  sleep 1
  rm ${torgate_pid}
  exit 1
}
trap torgate/exit EXIT

source config

tor -f ${PWD}/torrc &
sleep 1
echo "--------------------------------------------------------------------------"
echo ""


echo "${server} privoxy:"
cat privoxy
privoxy --pidfile "${PWD}/${privoxy_pid}" privoxy
# TODO: screen
read
