#!/bin/bash
cd ${1}
echo $$ > torgate.pid
function torgate/exit() {
  source config
  echo "Stopping delegated: ${mid_tor_host}:${mid_tor_http}..." > torgate.log
  delegated -Fkill -P${mid_tor_host}:${mid_tor_http} > delegated.log

  _pid=$(cat delegated.log | \
         sed s/.*kill\(//  | \
         sed s/,.*//)

  # force kill
  if ! test -z "${_pid}" ; then kill ${_pid}; fi

  sleep 1
  rm torgate.pid
  exit 1
}
trap torgate/exit EXIT
source config
tor -f ${PWD}/torrc
# TODO: SOCKS port check on not exists? abort
delegated -S -Tx -fv -P${mid_tor_host}:${mid_tor_http} SERVER=http SOCKS=${mid_tor_host}:${mid_tor_listen}
read
